### ISSUE TITLE
Enablement for All Languages

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mjbvz/vscode-jsdoc-markdown-highlighting#19]
Would it be possible to implement Markdown rendering in all languages? I currently use Markdown to format my comments in every project, so this would be wonderful.

**Comment by mjbvz** [comment]
I don't think this is possible (or at leastI don't think you can do it correctly). This needs to be implemented per-language to handle the specific of each language's comment syntax and each language's grammar

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mjbvz/vscode-jsdoc-markdown-highlighting/issues/19#issuecomment-1853059617

@mjbvz, then do you think you could allow your extension to switch between a whitelist and blacklist using a boolean configuration option? If it defaulted to a whitelist, it would continue to act as it does, but the user could change it to a blacklist, allowing it to be disabled solely in languages which it breaks. I don't think you provide the versatility of your extension enough credit.
