### ISSUE TITLE
Support Markdown links to files of workspace in JSDoc/TSDoc

### ISSUE THREAD

**Issue by AnyhowStep** [mjbvz/vscode-jsdoc-markdown-highlighting#5]
I made the feature request here, to the VS Code repo,
https://github.com/microsoft/vscode/issues/97739

But after updating to the latest version of VS Code, I found that syntax highlighting was broken.

So, I looked around and found this,
https://github.com/microsoft/vscode/issues/84626

Which led me here.

So, I assume my feature request belongs here, instead.

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/issues/86564

This is not related to syntax highlighting, rather how VS Code renders JSDocs
